services:
  web:
    image: slavav679/pet-family:v1.5
    ports:
      - "8181:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - postgres
      - minio
      - seq
      
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: "PetFamilyDb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:8050"

  mongodb:
    container_name: 'pet_mongodb'
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    volumes:
      - mongo_data:/data/db
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:81

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio:/var/lib/minio/data
    command: server --console-address ":9001" /data
    restart: always
  
  nginx:
    image: nginx:latest
    ports:
      - "8282:8282"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always

volumes:
  pgadmin:
  postgres-data:
  mongo_data:
  minio_data:
